services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanager-week10-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "14330:1433"
    volumes:
      - taskmanager-sql-data:/var/opt/mssql
    restart: unless-stopped
  seq:
    image: datalust/seq:latest
    container_name: taskmanager-seq
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:80"
    volumes:
      - taskmanager-seq-data:/data
    restart: unless-stopped

  api:
    build:
      context: ./TaskManagerApi
      dockerfile: Dockerfile
    container_name: taskmanager-week10-api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__TaskManagerConnection: "Server=sqlserver,1433;Database=TaskManagerDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;Encrypt=False"
      Seq__ServerUrl: "http://seq"
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
      - seq
    restart: on-failure

volumes:
  taskmanager-sql-data:
  taskmanager-seq-data: